"""
===============================================================================
Python Programming Foundation
Module 13 - Lambda Functions

Project 06: Sales Report Generator

Difficulty:
Intermediate

Estimated Completion Time:
60-75 Minutes

Objective:
Create a sales report generator using lambda functions, map(), filter(), and
sorted() to process sales data, calculate revenue, classify performance, and
generate business insights.

This project demonstrates how functional programming techniques can be applied
to real-world sales data processing tasks.

Python Version:
3.13+

===============================================================================
"""


# =============================================================================
# Project Description
# =============================================================================

"""
Problem Statement:
------------------

A company collects daily sales information from different sales employees.

The management team needs a simple reporting system that can:

- Calculate revenue generated by each salesperson.
- Identify successful sales employees.
- Classify sales performance.
- Rank employees based on revenue.
- Generate a sales performance report.


Functional Requirements:
-----------------------

The program must:

1. Store sales records.
2. Calculate revenue using map().
3. Assign performance categories.
4. Filter successful sales records.
5. Sort sales records by revenue.
6. Display a sales report.


Prerequisites:
--------------

Learners should understand:

- Lambda functions
- map()
- filter()
- sorted()
- key parameter
- Lists
- Dictionaries


Constraints:
------------

Do not use:

- Import statements
- External libraries
- Classes
- File handling
- Advanced programming concepts


Implementation Roadmap:
-----------------------

Step 1:
Create sales records.

Step 2:
Use map() to calculate revenue.

Step 3:
Use lambda functions to classify performance.

Step 4:
Use filter() to find successful sales.

Step 5:
Use sorted() to rank sales employees.

Step 6:
Display the final report.

===============================================================================
"""


# =============================================================================
# Sales Dataset
# =============================================================================

sales_records = [
    {
        "employee": "Ali",
        "units_sold": 120,
        "price_per_unit": 1500
    },
    {
        "employee": "Sara",
        "units_sold": 90,
        "price_per_unit": 1800
    },
    {
        "employee": "Ahmed",
        "units_sold": 150,
        "price_per_unit": 2000
    },
    {
        "employee": "Fatima",
        "units_sold": 70,
        "price_per_unit": 2500
    },
    {
        "employee": "Usman",
        "units_sold": 50,
        "price_per_unit": 1200
    }
]


# =============================================================================
# Step 1: Calculate Revenue Using map()
# =============================================================================

sales_with_revenue = list(
    map(
        lambda sale: {
            **sale,
            "revenue": (
                sale["units_sold"] *
                sale["price_per_unit"]
            )
        },
        sales_records
    )
)


# =============================================================================
# Step 2: Add Performance Category
# =============================================================================

sales_with_category = list(
    map(
        lambda sale: {
            **sale,
            "performance": (
                "Excellent"
                if sale["revenue"] >= 250000
                else "Good"
                if sale["revenue"] >= 150000
                else "Average"
            )
        },
        sales_with_revenue
    )
)


# =============================================================================
# Step 3: Filter Successful Sales Employees
# =============================================================================

successful_sales = list(
    filter(
        lambda sale: sale["revenue"] >= 150000,
        sales_with_category
    )
)


# =============================================================================
# Step 4: Sort Sales Records By Revenue
# =============================================================================

ranked_sales = sorted(
    sales_with_category,
    key=lambda sale: sale["revenue"],
    reverse=True
)


# =============================================================================
# Sales Performance Report
# =============================================================================

print("=" * 70)
print("SALES PERFORMANCE REPORT")
print("=" * 70)

rank = 1

for sale in ranked_sales:
    print(
        f"Rank: {rank}\n"
        f"Employee: {sale['employee']}\n"
        f"Units Sold: {sale['units_sold']}\n"
        f"Revenue: Rs. {sale['revenue']}\n"
        f"Performance: {sale['performance']}\n"
    )

    rank += 1


print("=" * 70)
print(f"Total Employees: {len(sales_with_category)}")
print(f"Successful Employees: {len(successful_sales)}")
print("=" * 70)


"""
===============================================================================
Sample Input:
===============================================================================

{
    "employee": "Ali",
    "units_sold": 120,
    "price_per_unit": 1500
}


===============================================================================
Sample Output:
===============================================================================

======================================================================
SALES PERFORMANCE REPORT
======================================================================

Rank: 1
Employee: Ahmed
Units Sold: 150
Revenue: Rs. 300000
Performance: Excellent

Rank: 2
Employee: Ali
Units Sold: 120
Revenue: Rs. 180000
Performance: Good

Rank: 3
Employee: Fatima
Units Sold: 70
Revenue: Rs. 175000
Performance: Good

Rank: 4
Employee: Sara
Units Sold: 90
Revenue: Rs. 162000
Performance: Good

Rank: 5
Employee: Usman
Units Sold: 50
Revenue: Rs. 60000
Performance: Average

======================================================================
Total Employees: 5
Successful Employees: 4
======================================================================


===============================================================================
Detailed Explanation:
===============================================================================

This project applies lambda functions to a business reporting workflow.

The first map() operation transforms sales records by calculating revenue.

Example:

lambda sale:
    sale["units_sold"] * sale["price_per_unit"]


The second map() operation adds performance categories based on revenue.

The filter() function selects employees whose revenue reaches the target.

The sorted() function ranks employees:

sorted(
    sales,
    key=lambda sale: sale["revenue"],
    reverse=True
)


The key parameter defines which value should be used for comparison.


===============================================================================
Code Walkthrough:
===============================================================================

1. Sales Dataset

Stores employee sales information.

2. Revenue Calculation

map() creates new records containing revenue values.

3. Performance Classification

lambda expressions assign performance levels.

4. Filtering

filter() finds successful employees.

5. Ranking

sorted() creates the final ranking report.


===============================================================================
Best Practices:
===============================================================================

- Use lambda functions for short operations.
- Keep transformation steps separate.
- Use meaningful dictionary keys.
- Use sorted() key functions for ranking.
- Prefer readable code over complicated one-line expressions.


===============================================================================
Common Mistakes:
===============================================================================

1. Incorrect revenue calculation.

2. Sorting by the wrong dictionary key.

3. Using filter() for transformation tasks.

4. Writing long lambda expressions.


===============================================================================
Possible Improvements:
===============================================================================

- Add monthly sales tracking.
- Add sales targets.
- Calculate employee commissions.
- Generate regional sales reports.


===============================================================================
Bonus Challenges:
===============================================================================

1. Find the highest revenue employee.

2. Calculate total sales manually.

3. Add product categories.

4. Create a sales recommendation system.


===============================================================================
Real-World Applications:
===============================================================================

Similar techniques are used in:

- Sales dashboards
- Business intelligence systems
- Reporting applications
- Data analysis workflows
- Machine learning data preparation


===============================================================================
Key Learning Outcomes:
===============================================================================

After completing this project, learners should understand:

✓ Transforming sales data with map()
✓ Filtering business records
✓ Ranking data using sorted()
✓ Using lambda functions in analytics
✓ Building practical data processing systems

===============================================================================
"""